name: Naukri Automation

on:
  schedule:
    # Active: Every 30 min between 9 AM–8 PM IST (all days)
    - cron: "0,15 2-15 * * *"

  workflow_dispatch:

jobs:
  run-automation:
    runs-on: ubuntu-latest

    env:
      NAUKRI_USERNAME: ${{ secrets.NAUKRI_USERNAME }}
      NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libxss1 \
            libasound2t64 \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libgtk-3-0 \
            libgbm1 \
            libxshmfence1


      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run Selenium Test
        run: mvn test --batch-mode -Dsurefire.useFile=false

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            screenshot_*.png
          if-no-files-found: warn
          compression-level: 6
          overwrite: true
          include-hidden-files: false
